dist: focal
language: python
env:
  global:
   - POETRY_VERSION="1.6.0"
python:
 - "3.10"
sudo: required
before_script:
  - sudo ssh -o StrictHostKeyChecking=no -fNT -4L 443:llb2.dev.mostlylab.com:443 mostlyai@ssh.dev.mostlylab.com
  - sudo bash -c 'echo "127.0.0.1 llb2.dev.mostlylab.com" >> /etc/hosts'
install:
  - pip install poetry==$POETRY_VERSION
  - poetry config virtualenvs.create false
  - poetry install -v --no-interaction --no-ansi --no-root  # Install dependencies
jobs:
  include:
    - name: Tests - static analysis [mypy, black, isort]
      if: branch NOT IN (test, main) AND tag IS NOT present
      script:
        # - poetry run mypy mostlyai/
        - poetry run black --check .
        - poetry run isort --check .
      before_script: skip

    - name: Tests - unit
      if: branch NOT IN (test, main) AND tag IS NOT present
      script: poetry run pytest tests/unit -vv
