name: "SDK Installation Test"

on:
    workflow_call:
        inputs:
          runner_type:
            type: string
            default: 'ubuntu-latest'

env:
    PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    FORCE_COLOR: "1"

jobs:
    run-pip-install:
        runs-on: ${{ inputs.runner_type }}
        permissions:
            contents: read
            packages: write
        steps:
          - name: Setup | Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 1
                submodules: 'true'

          - name: Setup | uv
            uses: astral-sh/setup-uv@v5
            with:
                enable-cache: false
                python-version: '3.10'

          - name: Setup | Dependencies
            run: |
              uv venv
              uv pip install ".[local]"
